### ISSUE TITLE
runStreme() does not return evalue

### ISSUE THREAD

**Issue by mniederhuber** [snystrom/memes#102]
I'm trying to track down if this is a bug or not, but `runStreme()` only returns `pval` for discovered motifs and not `eval` which I believe should also be calculated. 
Going to see if that's because it's not in the raw streme output or something with how the output is parsed and the dataframe is generated. 

using `memes v1.2.5`

**Comment by mniederhuber** [comment]
so no bug, `evalue` was a recent addition to `streme` in meme suite. Adding `test_log_evalue` and `test_evalue` to `streme_motif_stats` errors out since those columns are missing in `meme-5.3.3` (and earlier) `streme` xml output. 

Easy fix if to include those columns, just need to have `meme-5.4.1`

**Comment by snystrom** [comment]
Hey Matt. I do actually consider not supporting the latest meme suite version a bug. Is it that when you update to meme 5.4.1 you get what you need? Or should I add some features to the parser for meme versions later than `5.3.3`?

**Comment by snystrom** [comment]
For reference, this is not the first time the authors have made changes to streme. An example of how I've handled this before lives in the codebase [here](https://github.com/snystrom/memes/blob/master/R/streme.R#L313-L322). It sounds like you may already have a fix in mind, so if you do and implement it like this you're welcome to submit a PR, or I can get to it sometime this weekend.

**Comment by mniederhuber** [comment]
It does look like it's just a matter of using the current version of meme-suite. The only changes I made to `memes` was within `streme.R` to include the `evalue` columns to `dbl_cols` and subsequent renaming of `evalue` to `eval`. But these don't seem to be necessary, at least for what I'm doing currently. ie. evalue columns correctly return after `runStreme()` regardless of making those changes.
