### ISSUE TITLE
Small typo in error message

### ISSUE THREAD

**Issue by SorenHeidelbach** [snystrom/memes#103]
https://github.com/snystrom/memes/blob/457c24c2c9a1590d125351e91c62eb1b9e8bd25c/R/meme.R#L89

The parameter is "parse_genomic_coord", but the error message says "parse_genomic_coords", just a small thing, but caused a bit of confusion.

**Comment by snystrom** [comment]
Ah, nice catch, sorry for the confusion! I'll push a fix soon.

**Comment by snystrom** [comment]
This is fixed now, sorry for such a long delay. Thanks again for reporting, I wound up finding this typo in several places in the codebase & documentation, so this could've really been tripping folks up in multiple places.
