### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by sa95078** [snystrom/memes#71]
I ran into issues with installation. Here is the error message: 
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘memes’ in namespaceExport(ns, exports):
 undefined exports: TODO:, import?, below, change, to, tomtom.xml, use
Error: loading failed
Execution halted
ERROR: loading failed

Thank you for your help, 

James

**Comment by snystrom** [comment]
Hi James,

Sorry for the issue! I just pushed the fix, it should now install correctly.

Thanks for trying the package!
