### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by ywang1993** [snystrom/memes#82]
When I try to install it, there is an error message stating that "package 'memes' requires R >= 4.1". However, the final version of R 4.1.0 has not been released yet. Is it possible to install it using older R versions?

**Comment by snystrom** [comment]
Thanks for trying the package! Unfortunately, depending on R >= 4.1 is a requirement for the next Bioconductor release. In the mean time I made a separate branch without this requirement which you can install like this: `remotes::install_github("snystrom/memes", ref = "no-r-4")`

Once the Bioconductor version is released I will probably not update this branch often, but for now it should do the job!

**Comment by ywang1993** [comment]
Thanks for the quick reply! It works now :)
