### ISSUE TITLE
runfimo() throws an error when there are no results found and an outdir provided

### ISSUE THREAD

**Issue by tensulin** [snystrom/memes#86]
If the text = F and outdir param with runFimo is set and no Fimo found no results then the function will throw an error

**Comment by snystrom** [comment]
Ah, good catch. I will change the behavior to instead print an informative message and return `NULL` instead (which is the behavior if `text == FALSE`). I'll ping here when it's fixed (hopefully in the next day or two).

Thanks for the issue report!

**Comment by tensulin** [comment]
You are welcome! Thanks for the fix and for the package! It is really helpfull

**Comment by snystrom** [comment]
Ok, I think I got the bug fixed. I pushed the changes to the Bioconductor release branch as well, but I would suggest installing the development version from github instead using:

`remotes::install_github("snystrom/memes")` to ensure you get the bugfix release (it usually takes a bit for the build to propagate to Bioconductor servers). The current development version is identical to the bioconductor release, so you shouldn't have any issues using this version for now.

Thanks again for the bug report. If you still have the issue after you update, feel free to reopen the issue.
