### ISSUE TITLE
Error in to_df(.) : could not find function "to_df"

### ISSUE THREAD

**Issue by mdozmorov** [snystrom/memes#88]
Hi @snystrom, thanks for the package. I'm running it from a Docker container, going through the `integrative_analysis.Rmd` vignette. I cannot seem to find the [to_df()](https://github.com/snystrom/memes/blob/9a52d783bb1cc5a9b5a0810414ac9d9d0f81ab4b/vignettes/integrative_analysis.Rmd#L117) function, with "Error in to_df(.) : could not find function "to_df"". Googling it is not easy. I tried something like the below, but, apparently, it won't work because I'm getting another error at the [database filtering step](https://github.com/snystrom/memes/blob/9a52d783bb1cc5a9b5a0810414ac9d9d0f81ab4b/vignettes/integrative_analysis.Rmd#L154), "Error: Can't transform a data frame with duplicate names." Any advice?
```
to_df <- function(x) {
  class(x) <- "data.frame"
  attr(x, "row.names") <- .set_row_names(length(x[[1]]))
  x
}
```

**Comment by snystrom** [comment]
Oh interesting... That function is exported from `universalmotif` (ie. `universalmotif::to_df()`), so maybe load that library.

**Comment by snystrom** [comment]
Also, are you doing this on your own data, or are you just repeating verbatim the analysis in the vignette? If you're using your own data, and using `universalmotif::to_df()` doesn't fix the issue, could you check whether `length(names(your_motifs)) == length(unique(names(your_motifs)))` is `TRUE`?

**Comment by mdozmorov** [comment]
Yes, just found that in my local installation of universalmotif v.1.10.1 I have `to_df()` and `to_list()`. Seems like the issue is with the Docker image, it installs universalmotif v.1.8.5, which doesn't have those functions.  Updating universalmotif within the container solves the error.

**Comment by snystrom** [comment]
Great! Was this with the `memes_docker` container? I can fix that issue if so.

**Comment by mdozmorov** [comment]
Yes, I ran `snystrom/memes_docker:devel`

**Comment by snystrom** [comment]
Ah, I think the autobuilds have failed since Dockerhub changed their policy! I'll push up a new build & try to get those back on schedule.
