### ISSUE TITLE
runStreme() error

### ISSUE THREAD

**Issue by ivangalvan** [snystrom/memes#90]
Hi,

I found an error when using the runStreme() function in the following code:

``
data("example_peaks", package = "memes")
``
``
dm.genome <- BSgenome.Dmelanogaster.UCSC.dm6::BSgenome.Dmelanogaster.UCSC.dm6
``
``
sequences <- example_peaks %>%  resize(100, "center") %>% get_sequence(dm.genome)
``
``
streme_results <- runStreme(sequences, control = "shuffle")
``

Error: Can't subset columns that don't exist.
Column `from` doesn't exist.

Backtrace:
  1. memes::runStreme(sequences, control = "shuffle")
 11. dplyr:::select.data.frame(., -"from")
 12. tidyselect::eval_select(expr(c(...)), .data)
 13. tidyselect:::eval_select_impl(...)
 21. tidyselect:::vars_select_eval(...)
 22. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 23. tidyselect:::eval_c(expr, data_mask, context_mask)
 24. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 25. tidyselect:::walk_data_tree(new, data_mask, context_mask)
 26. tidyselect:::as_indices_sel_impl(...)
 27. tidyselect:::as_indices_impl(x, vars, strict = strict)
 28. tidyselect:::chr_as_locations(x, vars)
 29. vctrs::vec_as_location(x, n = length(vars), names = vars)
 31. vctrs:::stop_subscript_oob(...)
 32. vctrs:::stop_subscript(...)

Would you know what could be the bug? I tried to figure out without success where is the `dplyr:::select.data.frame(., -"from")` command in your code.

Could you provide an example code to run the runStreme() function properly?

Thank you

**Comment by snystrom** [comment]
Hey, thanks for reporting the issue & providing a reproducible example, I'll take a look this evening. `runStreme` has a few odd bugs in that recently cropped up that I need to chase down.

Can you try running it again with:

```
streme_results <- runStreme(sequences, control = sequences)
```

Just as a quick check to see if the issue is with the "shuffle" call?

**Comment by ivangalvan** [comment]
Thank you for your quick reply,

Unfortunately, the same error appears with your command and then the issue seems not to be related with the control argument.

**Comment by snystrom** [comment]
Great, thanks for trying that out! Swamped w/ work at the moment, but should have some time this evening. Hopefully can patch it quick for you.

**Comment by snystrom** [comment]
In the mean time, `runDreme` is probably the best substitute.

**Comment by snystrom** [comment]
Alternately, you can run the Streme webtool and import the XML results with `importStremeXML()`

**Comment by snystrom** [comment]
Hey Iván,

I'm having trouble reproducing this error. Can you post the output of `sessionInfo()` and the output of `check_meme_install()`? 

Finally, can you try running:
```
streme_results <- runStreme(sequences, control = "shuffle", outdir = "debug")
```

Then upload the `streme.xml` file output from the `debug/` directory (created in your R project working directory where you run the command).

Thanks for helping me get to the bottom of this!

**Comment by snystrom** [comment]
Oh and does:

```
x <- universalmotif::create_sequences()
runStreme(x)
```

Also cause the same error?

**Comment by ivangalvan** [comment]
Hi Spencer,

I found the same error with your suggestions. 

The `check_meme_install` seems good:

checking main install
✓ /home/igalvan/meme/bin
checking util installs
✓ /home/igalvan/meme/bin/dreme
✓ /home/igalvan/meme/bin/ame
✓ /home/igalvan/meme/bin/fimo
✓ /home/igalvan/meme/bin/tomtom
✓ /home/igalvan/meme/bin/meme
✓ /home/igalvan/meme/bin/streme

My session ifno is:

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=es_ES.UTF-8       LC_NUMERIC=C               LC_TIME=es_ES.UTF-8        LC_COLLATE=es_ES.UTF-8     LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=es_ES.UTF-8   
 [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.7          GenomicRanges_1.46.1 GenomeInfoDb_1.30.0  IRanges_2.28.0       S4Vectors_0.32.3     BiocGenerics_0.40.0  magrittr_2.0.1       memes_1.2.0         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7                            lattice_0.20-45                       tidyr_1.1.4                           ps_1.6.0                             
 [5] Rsamtools_2.10.0                      Biostrings_2.62.0                     ggseqlogo_0.1                         rprojroot_2.0.2                      
 [9] utf8_1.2.2                            R6_2.5.1                              universalmotif_1.12.1                 ggplot2_3.3.5                        
[13] pillar_1.6.4                          zlibbioc_1.40.0                       rlang_0.4.12                          rstudioapi_0.13                      
[17] R.utils_2.11.0                        R.oo_1.24.0                           Matrix_1.3-4                          BSgenome.Dmelanogaster.UCSC.dm6_1.4.1
[21] desc_1.4.0                            BiocParallel_1.28.2                   readr_2.1.1                           cmdfun_1.0.2                         
[25] RCurl_1.98-1.5                        munsell_0.5.0                         DelayedArray_0.20.0                   compiler_4.1.2                       
[29] rtracklayer_1.54.0                    pkgconfig_2.0.3                       tidyselect_1.1.1                      SummarizedExperiment_1.24.0          
[33] tibble_3.1.6                          GenomeInfoDbData_1.2.7                matrixStats_0.61.0                    XML_3.99-0.8                         
[37] fansi_0.5.0                           crayon_1.4.2                          tzdb_0.2.0                            withr_2.4.3                          
[41] GenomicAlignments_1.30.0              MASS_7.3-54                           bitops_1.0-7                          R.methodsS3_1.8.1                    
[45] grid_4.1.2                            gtable_0.3.0                          lifecycle_1.0.1                       scales_1.1.1                         
[49] cli_3.1.0                             XVector_0.34.0                        fs_1.5.1                              testthat_3.1.0                       
[53] xml2_1.3.3                            ellipsis_0.3.2                        generics_0.1.1                        vctrs_0.3.8                          
[57] rjson_0.2.20                          restfulr_0.0.13                       tools_4.1.2                           BSgenome_1.62.0                      
[61] Biobase_2.54.0                        glue_1.5.1                            purrr_0.3.4                           hms_1.1.1                            
[65] MatrixGenerics_1.6.0                  processx_3.5.2                        pkgload_1.2.4                         parallel_4.1.2                       
[69] yaml_2.2.1                            colorspace_2.0-2                      BiocManager_1.30.16                   BiocIO_1.4.0                         
[73] usethis_2.1.3   


It seems there is in some place of the code the "from" column but data do not have this column. What do you think?

Thank you

**Comment by ivangalvan** [comment]
Hi again,

I found the outputs of streme in the debug folder and now, I realized that the error comes by using the `importStremeXML()` function. However the `importDremeXML()` is working fine.

**Comment by snystrom** [comment]
Yeah s mething is happening at the XML generation step I think where it's leaving out a column it usually has. Can you upload the streme.xml file to this issue and I'll take a look at it.

**Comment by snystrom** [comment]
This could be a bug in STREME or they may have changed the behavior of STREME. Can you also post the version of the meme suite you are using? On the bash terminal `streme --version` or in R: `runStreme(sequences, "shuffle", version = TRUE, silent = FALSE)`.

**Comment by ivangalvan** [comment]
Sure, version is 5.4.1.

I can't upload the .xml file, it is not supported by github. I copy that here:

############################


<STREME version="5.4.1" release="Sat Aug 21 19:23:23 2021 -0700">
  <model>
    <command_line>streme --p /tmp/RtmpZqrcO7/filead01f191a2e9b.fa --oc debug --dna</command_line>
    <train_positives count="10" positions="1000" maxlen="100" file="/tmp/RtmpZqrcO7/filead01f191a2e9b.fa"/>
    <train_negatives count="10" positions="1000" from="shuffled"/>
    <test_positives count="0" positions="0"/>
    <test_negatives count="0" positions="0"/>
    <alphabet name="DNA" like="dna">
      <letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
      <letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
      <letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
      <letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
      <letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
      <letter id="V" symbol="V" equals="ACG" name="Not T"/>
      <letter id="H" symbol="H" equals="ACT" name="Not G"/>
      <letter id="D" symbol="D" equals="AGT" name="Not C"/>
      <letter id="B" symbol="B" equals="CGT" name="Not A"/>
      <letter id="M" symbol="M" equals="AC" name="Amino"/>
      <letter id="R" symbol="R" equals="AG" name="Purine"/>
      <letter id="W" symbol="W" equals="AT" name="Weak"/>
      <letter id="S" symbol="S" equals="CG" name="Strong"/>
      <letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
      <letter id="K" symbol="K" equals="GT" name="Keto"/>
    </alphabet>
    <strands>both</strands>
    <sequence_db A="0.281" C="0.22" G="0.22" T="0.281"/>
    <background_frequencies source="--negatives--" order="2">
      <alphabet_array>
        <value letter_id="A">0.281</value>
        <value letter_id="C">0.22</value>
        <value letter_id="G">0.22</value>
        <value letter_id="T">0.281</value>
      </alphabet_array>
    </background_frequencies>
    <stop nmotifs="5"/>
    <objfun>Differential Enrichment</objfun>
    <test>Fisher Exact Test</test>
    <minw>8</minw>
    <maxw>15</maxw>
    <kmer>3</kmer>
    <hofract>0.1</hofract>
    <neval>25</neval>
    <nref>4</nref>
    <niter>20</niter>
    <patience>3</patience>
    <seed>0</seed>
    <useer>no</useer>
    <minscore>0</minscore>
    <ignore_depth>5</ignore_depth>
    <nsubsets>1</nsubsets>
    <min_pal_ratio>0.85</min_pal_ratio>
    <max_pal_ed>5</max_pal_ed>
    <cand>no</cand>
    <experimental>no</experimental>
    <totallength>0</totallength>
    <align>center</align>
    <host>supek15</host>
  </model>
  <motifs>
    <motif id="1-RCAGTTAAV" alt="STREME-1" width="9" initial_width="8" seed="ACAGTTAAG" score_threshold="9.1828" train_pos_count="7" train_neg_count="0" train_log_pvalue="-2.81023" train_pvalue="1.5e-003" train_dtc="-1.0" train_bernoulli="-1" test_pos_count="0" test_neg_count="0" test_log_pvalue="0" test_pvalue="1.0e+000" test_log_evalue="0.69897" test_evalue="5.0e+000" test_dtc="-1.0" test_bernoulli="-1" is_palindromic="no" elapsed_time="0.1" total_sites="7" site_distr=" 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0" max_sites="1" site_hist=" 0 7">
      <pos A="0.565554" C="0.144405" G="0.284377" T="0.00566434"/>
      <pos A="0.00566434" C="0.984239" G="0.00443253" T="0.00566434"/>
      <pos A="0.845498" C="0.00443253" G="0.00443253" T="0.145637"/>
      <pos A="0.00566434" C="0.00443253" G="0.984239" T="0.00566434"/>
      <pos A="0.00566434" C="0.00443253" G="0.00443253" T="0.985471"/>
      <pos A="0.00566434" C="0.00443253" G="0.144405" T="0.845498"/>
      <pos A="0.845498" C="0.00443253" G="0.144405" T="0.00566434"/>
      <pos A="0.845498" C="0.00443253" G="0.00443253" T="0.145637"/>
      <pos A="0.285609" C="0.284377" G="0.424349" T="0.00566434"/>
    </motif>
    <motif id="2-CCSTCCCT" alt="STREME-2" width="8" initial_width="7" seed="CCCTCCCT" score_threshold="10.489" train_pos_count="6" train_neg_count="0" train_log_pvalue="-2.26616" train_pvalue="5.4e-003" train_dtc="-1.0" train_bernoulli="-1" test_pos_count="0" test_neg_count="0" test_log_pvalue="0" test_pvalue="1.0e+000" test_log_evalue="0.69897" test_evalue="5.0e+000" test_dtc="-1.0" test_bernoulli="-1" is_palindromic="no" elapsed_time="0.1" total_sites="6" site_distr=" 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0" max_sites="1" site_hist=" 0 6">
      <pos A="0.00650367" C="0.981903" G="0.00508932" T="0.00650367"/>
      <pos A="0.167217" C="0.660477" G="0.00508932" T="0.167217"/>
      <pos A="0.00650367" C="0.647941" G="0.339051" T="0.00650367"/>
      <pos A="0.00650367" C="0.00508932" G="0.00508932" T="0.983318"/>
      <pos A="0.00650367" C="0.981903" G="0.00508932" T="0.00650367"/>
      <pos A="0.00650367" C="0.981903" G="0.00508932" T="0.00650367"/>
      <pos A="0.00650367" C="0.981903" G="0.00508932" T="0.00650367"/>
      <pos A="0.167217" C="0.00508932" G="0.00508932" T="0.822605"/>
    </motif>
    <motif id="3-AGACCCCAAAAAA" alt="STREME-3" width="13" initial_width="5" seed="AGACCCCAAAAAA" score_threshold="2.577" train_pos_count="5" train_neg_count="0" train_log_pvalue="-1.78904" train_pvalue="1.6e-002" train_dtc="-1.0" train_bernoulli="-1" test_pos_count="0" test_neg_count="0" test_log_pvalue="0" test_pvalue="1.0e+000" test_log_evalue="0.69897" test_evalue="5.0e+000" test_dtc="-1.0" test_bernoulli="-1" is_palindromic="no" elapsed_time="0.2" total_sites="5" site_distr=" 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0" max_sites="1" site_hist=" 0 5">
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.0255" C="0.0199545" G="0.929045" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.0255" C="0.929045" G="0.0199545" T="0.0255"/>
      <pos A="0.0255" C="0.929045" G="0.0199545" T="0.0255"/>
      <pos A="0.0255" C="0.929045" G="0.0199545" T="0.0255"/>
      <pos A="0.0255" C="0.929045" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
    </motif>
    <motif id="4-GAYTCGTAWWB" alt="STREME-4" width="11" initial_width="8" seed="GATTCGTATAT" score_threshold="2.74945" train_pos_count="5" train_neg_count="0" train_log_pvalue="-1.78904" train_pvalue="1.6e-002" train_dtc="-1.0" train_bernoulli="-1" test_pos_count="0" test_neg_count="0" test_log_pvalue="0" test_pvalue="1.0e+000" test_log_evalue="0.69897" test_evalue="5.0e+000" test_dtc="-1.0" test_bernoulli="-1" is_palindromic="no" elapsed_time="0.6" total_sites="5" site_distr=" 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" max_sites="1" site_hist=" 0 5">
      <pos A="0.00976471" C="0.00764119" G="0.972829" T="0.00976471"/>
      <pos A="0.974953" C="0.00764119" G="0.00764119" T="0.00976471"/>
      <pos A="0.00976471" C="0.490235" G="0.00764119" T="0.492359"/>
      <pos A="0.00976471" C="0.00764119" G="0.00764119" T="0.974953"/>
      <pos A="0.00976471" C="0.972829" G="0.00764119" T="0.00976471"/>
      <pos A="0.00976471" C="0.00764119" G="0.972829" T="0.00976471"/>
      <pos A="0.00976471" C="0.00764119" G="0.248938" T="0.733656"/>
      <pos A="0.733656" C="0.00764119" G="0.00764119" T="0.251062"/>
      <pos A="0.492359" C="0.00764119" G="0.00764119" T="0.492359"/>
      <pos A="0.492359" C="0.00764119" G="0.00764119" T="0.492359"/>
      <pos A="0.00976471" C="0.248938" G="0.248938" T="0.492359"/>
    </motif>
    <motif id="5-AAAATGAAA" alt="STREME-5" width="9" initial_width="9" seed="AAAATGAAA" score_threshold="5.76413" train_pos_count="6" train_neg_count="1" train_log_pvalue="-1.54306" train_pvalue="2.9e-002" train_dtc="-1.0" train_bernoulli="-1" test_pos_count="0" test_neg_count="0" test_log_pvalue="0" test_pvalue="1.0e+000" test_log_evalue="0.69897" test_evalue="5.0e+000" test_dtc="-1.0" test_bernoulli="-1" is_palindromic="no" elapsed_time="0.7" total_sites="6" site_distr=" 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" max_sites="1" site_hist=" 0 6">
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.0255" C="0.0199545" G="0.0199545" T="0.934591"/>
      <pos A="0.0255" C="0.0199545" G="0.929045" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
      <pos A="0.934591" C="0.0199545" G="0.0199545" T="0.0255"/>
    </motif>
  </motifs>
  <reason_for_stopping>Stopped because maximum number of motifs (5) reached.</reason_for_stopping>
  <run_time cpu="0.70"/>
</STREME>

**Comment by snystrom** [comment]
Thanks for checking!

Sometimes dragging + dropping the file into the text box works. I'll try something else on my end also.

**Comment by snystrom** [comment]
Ah, got it! I was a MEME version behind. They've changed STREME behavior. I'll try to add a way to catch this that works for old & current versions. Thanks for reporting, I'll ping when I get the issue resolved.

**Comment by ivangalvan** [comment]
It sounds good! Thanks!

**Comment by snystrom** [comment]
This should be fixed now. The changes will propagate to bioc release & devel in a few days. For now, you can install the development version from github with:

`remotes::install_github("snystrom/memes")`

Thanks so much for reporting the issue, I hope your analysis goes well! And feel free to reopen this issue if the bug persists.

**Comment by ivangalvan** [comment]
Thank you very much! I confirm that now `importStremeXML()` is working properly!
