### ISSUE TITLE
error runinng runTomTom 

### ISSUE THREAD

**Issue by whywhowhat** [snystrom/memes#99]
Even for running example code of runTomTom(), causing following error : 
`Error: 'update_motifs' is not an exported object from 'namespace:universalmotif'`

Is there any specific or suitable version for using runTomTom() and `universalmotif` package?  
In the end, planning to run list of degenerated consensus for motif comparison.

**Comment by snystrom** [comment]
Can you post the output of `sessionInfo()`? Did you install `memes` from Bioconductor with `BiocManager::install("memes")`?

**Comment by snystrom** [comment]
Glad that was the fix! Good luck with your analysis!
